### PR TITLE
Now 2.0

### PR DESCRIPTION
**Pull request by paulogdm**
Please, don't merge it yet. Give Now permission to deploy.

### CODE REVIEW

**Comment by elsigh** [comment]
ok gave permission to deploy

**Comment by paulogdm** [comment]
@elsigh Please, do it again. Just pushed a new commit.

**Comment by elsigh** [comment]
gave authorizatoin again

**Comment by paulogdm** [comment]
It should be using the new version of Now (2.0). Did you deploy a Now 1.0 app to the same project?

**Comment by elsigh** [comment]
I don't think I understand the question...

**Comment by elsigh** [comment]
I don't mind just merging and going from there fwiw

**Comment by paulogdm** [comment]
By default, now should use the latest version of the platform, unless the project has Now 1.0 apps.
Check your dashboard and let me know.
I've introduced a new line of configuration to fix that.

**Comment by elsigh** [comment]
```

Failed to compile.
--
02:04:07 PM | ./components/Page.js
02:04:07 PM | SyntaxError: /zeit/35c5e86e/components/Page.js: Unexpected token, expected "," (45:47)
02:04:07 PM | 43 \|     href="/"
02:04:07 PM | 44 \|     onClick={async () => {
02:04:07 PM | > 45 \|       console.debug("login as guest", { process.env.DROPBOX_PUBLIC_TOKEN });
02:04:07 PM | \|                                                ^
02:04:07 PM | 46 \|       await storage.setAccessToken(process.env.DROPBOX_PUBLIC_TOKEN);
02:04:07 PM | 47 \|       // href is "/" so letting default event go through here = refresh
02:04:07 PM | 48 \|     }}

```

**Comment by elsigh** [comment]
I definitely pushed now1 builds to this project before..

**Comment by paulogdm** [comment]
It is building locally now.

**Comment by paulogdm** [comment]
Luckily for us, Now 2.0 has blazing fast builds :wink:

**Comment by elsigh** [comment]
still has a syntax error in the logging line. because the value uses dot-syntax it can't be standalone it needs an explicit key there I believe (or just remove the curlies)

**Comment by paulogdm** [comment]
Not anymore: https://chartcomposer-qa7riqdxw.now.sh/

**Comment by elsigh** [comment]
sweet! appears to be deployed and working in prod as intended. Thank you soooo very kindly. This change makes me 😄 and as ever I'm super impressed by the Zeit team (and you!)

**Comment by paulogdm** [comment]
Thanks for the kind words, don't forget to add the domain as a production domain: https://zeit.co/docs/v2/custom-domains
Stay tuned for more features soon!

**Pull request merged**
